## Flowers Recognition 

The Oxford Flowers 102 dataset is a collection of 102 flower categories commonly occurring in the United 
Kingdom. Each class consists of between 40 and 258 images. The images have large scale, pose and light 
variations. In addition, there are categories that have large variations within the category and several very 
similar categories. 
The dataset is divided into a training set, a validation set and a test set. The training set and validation set 
each consist of 10 images per class (a total of 1020 images each). The test set consists of the remaining 
6149 images (minimum 20 per class). Some tasks to consider: 
1. Modify some previously published architectures e.g., increase the network depth, reducing their 
parameters,  etc.  Explore  more  advanced  techniques  such  as  deformable  convolution,  dilated 
convolution (dilation>1) or visual prompt tuning for Transformers. 
2. Analyze the results of using fewer training images, i.e., few-shot learning 
3. Use  more  advanced  transformation  techniques  such  as  MixUp  (see  the  original  paper  and  its 
PyTorch implementation here) 
4. Try more advanced loss function such as triplet loss

In [ ]:
import platform

if platform.system() == "Darwin":  # macOS
    %pip install -r requirements_mac.txt
else:
    %pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.


### Environment Setup

This section setups the environment by doing the following:
1. Importing the dependencies
2. Checking if CUDA is available on device running this notebook
3. Setting up of transforms for data augmentation
4. Setting up data folder and downloading of datasets

In [2]:
# Import necessary libraries
import os
import time
import copy
import numpy as np
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm 

# Torch dependencies
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
from torchvision import datasets, models, transforms
from torch.utils.data import DataLoader
from torchsummary import summary  # For model architecture visualization

In [4]:
# Check device and set up environment, especially if CUDA is available
device = torch.device("mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu"))
print(f"Using device: {device}")

Using device: mps


In [ ]:
# Create two random tensors on the GPU
tensor_a = torch.randn(3, 3, device=device)
tensor_b = torch.randn(3, 3, device=device)

# Perform matrix multiplication
result = torch.matmul(tensor_a, tensor_b)

# Print the result
print("Tensor A:")
print(tensor_a)
print("\nTensor B:")
print(tensor_b)
print("\nResult of Matrix Multiplication:")

Tensor A:
tensor([[ 0.3279, -0.7582, -1.3762],
        [ 1.6719, -1.1975,  1.5821],
        [ 0.0403, -1.1838, -0.7464]], device='mps:0')

Tensor B:
tensor([[-1.3084,  0.0957,  0.1557],
        [ 0.7415, -0.7738,  1.6747],
        [-0.8811,  1.3196,  1.2208]], device='mps:0')

Result of Matrix Multiplication:
The computation was performed on the GPU.
tensor([[ 0.2213, -1.1980, -2.8988],
        [-4.4694,  3.1744,  0.1863],
        [-0.2729, -0.0650, -2.8874]], device='mps:0')
